### ISSUE TITLE
Max button is disabled after allow spending is approved once

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/sygma-widget#123]
**Context**:  After the user allows spending once, the UI disable the max button. 
![Max_not_work](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/b1e87d39-f4ae-4f01-9803-e78eb0548431)

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-widget/123?planning-poker) with Zenhub @Lykhoyda @mpetrunic @wainola

**Comment by Lykhoyda** [comment]
@mpetrunic should be solved by this PR https://github.com/sygmaprotocol/sygma-widget/pull/137

**Comment by mpetrunic** [comment]
@Lykhoyda Please just add that into description of your PR :)

**Comment by LyonSsS** [comment]
Retested on https://github.com/sygmaprotocol/sygma-widget/pull/137 but it is still an issue 
![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/ab7e0be2-c84c-459a-8bcf-4f92156c73a8)
![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/11a20f46-e156-49e0-b250-8b6e13571e8c)

**Comment by Lykhoyda** [comment]
Fixed in PR https://github.com/sygmaprotocol/sygma-widget/pull/137

**Comment by LyonSsS** [comment]
Retested on Core release branch and works fine 
![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/2b33b9c0-372d-4bdd-bdec-fe4e93993a49)
